name: Deploy To S3 And Invalidate Cloudfront

on:
  push:
    branches:
      - main

# actions/checkout : 라이브러리
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@4